import style from "@stylistic/eslint-plugin";
import type { Linter } from "eslint";
import importPlugin from "eslint-plugin-import-lite";
import perfectionist from "eslint-plugin-perfectionist";
import unicorn from "eslint-plugin-unicorn";
import globals from "globals";

export const BASE_CONFIG: Linter.Config = {
	languageOptions: {
		ecmaVersion: "latest",
		globals: {
			...globals.browser,
			document: "readonly",
			navigator: "readonly",
			window: "readonly",
		},
		parserOptions: {
			ecmaFeatures: {
				jsx: true,
			},
			ecmaVersion: "latest",
			sourceType: "module",
		},
		sourceType: "module",
	},
	plugins: {
		import: importPlugin,
		unicorn: unicorn,
		perfect: perfectionist,
	},
	linterOptions: {
		reportUnusedDisableDirectives: "error",
	},
	rules: {
		"accessor-pairs": [
			"error",
			{ enforceForClassMembers: true, setWithoutGet: true },
		],
		"array-callback-return": "error",

		"block-scoped-var": "error",
		"capitalized-comments": "off",
		"constructor-super": "error",
		curly: "error",
		"dot-notation": ["error", { allowKeywords: true }],
		eqeqeq: ["error", "smart"],
		"no-array-constructor": "error",
		"no-async-promise-executor": "error",
		"no-caller": "error",
		"no-case-declarations": "error",
		"no-class-assign": "error",
		"no-compare-neg-zero": "error",
		"no-console": ["error", { allow: ["warn", "error"] }],
		"no-control-regex": "error",
		"no-debugger": "error",
		"no-dupe-args": "error",
		"no-dupe-class-members": "error",
		"no-dupe-keys": "error",
		"no-duplicate-case": "error",
		"no-empty": "error",
		"no-eval": "error",
		"no-extend-native": "error",
		"no-extra-bind": "error",
		"no-extra-boolean-cast": "error",
		"no-fallthrough": "error",
		"no-func-assign": "error",
		"no-global-assign": "error",
		"no-implied-eval": "error",
		"no-import-assign": "error",
		"no-invalid-regexp": "error",
		"no-invalid-this": "error",
		"no-irregular-whitespace": "error",
		"no-iterator": "error",
		"no-labels": "error",
		"no-lone-blocks": "error",
		"no-lonely-if": "error",
		"no-loss-of-precision": "error",
		"no-misleading-character-class": "error",
		"no-multi-str": "error",
		"no-new": "error",
		"no-new-func": "error",
		"no-object-constructor": "error",
		"no-new-native-nonconstructor": "error",
		"no-new-wrappers": "error",
		"no-obj-calls": "error",
		"no-octal": "error",
		"no-octal-escape": "error",
		"no-proto": "error",
		"no-prototype-builtins": "error",
		"no-redeclare": "error",
		"no-regex-spaces": "error",
		"no-restricted-properties": [
			"error",
			{
				message:
					"Use `Object.getPrototypeOf` or `Object.setPrototypeOf` instead.",
				property: "__proto__",
			},
			{
				message: "Use `Object.defineProperty` instead.",
				property: "__defineGetter__",
			},
			{
				message: "Use `Object.defineProperty` instead.",
				property: "__defineSetter__",
			},
			{
				message: "Use `Object.getOwnPropertyDescriptor` instead.",
				property: "__lookupGetter__",
			},
			{
				message: "Use `Object.getOwnPropertyDescriptor` instead.",
				property: "__lookupSetter__",
			},
		],
		"no-self-compare": "error",
		"no-sequences": "error",
		"no-sparse-arrays": "error",
		"no-template-curly-in-string": "error",
		"no-this-before-super": "error",
		"no-throw-literal": "error",
		"no-undef": "error",
		"no-undef-init": "error",
		"no-unreachable": "error",
		"no-unreachable-loop": "error",
		"no-unsafe-finally": "error",
		"no-unsafe-negation": "error",
		"no-unused-vars": [
			"error",
			{
				args: "all",
				argsIgnorePattern: "^_",
				caughtErrors: "all",
				caughtErrorsIgnorePattern: "^_",
				destructuredArrayIgnorePattern: "^_",
				varsIgnorePattern: "^_",
				ignoreRestSiblings: true,
			},
		],
		"no-unassigned-vars": "error",
		"no-use-before-define": [
			"error",
			{ classes: false, functions: false, variables: true },
		],
		"no-useless-call": "error",
		"no-useless-catch": "error",
		"no-var": "error",
		"no-void": "error",
		"no-with": "error",
		"object-shorthand": ["error", "consistent-as-needed"],
		"prefer-const": "error",
		"prefer-promise-reject-errors": "error",
		"prefer-rest-params": "error",
		"prefer-spread": "error",
		"prefer-template": "error",
		yoda: ["error", "never"],

		// import plugin
		"import/first": "error",
		"import/no-duplicates": "error",
		"import/no-mutable-exports": "error",
		"import/no-named-default": "error",

		// unicorn plugin
		"unicorn/better-regex": "error",
		"unicorn/catch-error-name": "error",
		"unicorn/consistent-destructuring": "error",
		"unicorn/consistent-function-scoping": "error",
		"unicorn/custom-error-definition": "error",
		"unicorn/empty-brace-spaces": "error",
		"unicorn/error-message": "error",
		"unicorn/escape-case": "error",
		"unicorn/new-for-builtins": "error",
		"unicorn/no-abusive-eslint-disable": "error",
		"unicorn/no-array-for-each": "error",
		"unicorn/no-array-method-this-argument": "error",
		"unicorn/prefer-single-call": "error",
		"unicorn/no-await-expression-member": "error",
		"unicorn/no-console-spaces": "error",
		"unicorn/no-empty-file": "error",
		"unicorn/no-hex-escape": "error",
		"unicorn/no-instanceof-builtins": "error",
		"unicorn/no-invalid-remove-event-listener": "error",
		"unicorn/no-keyword-prefix": "error",
		"unicorn/no-lonely-if": "error",
		"unicorn/no-nested-ternary": "error",
		"unicorn/no-new-array": "error",
		"unicorn/no-new-buffer": "error",
		"unicorn/no-unnecessary-await": "error",
		"unicorn/no-useless-switch-case": "error",
		"unicorn/number-literal-case": "error",
		"unicorn/numeric-separators-style": [
			"error",
			{ number: { minimumDigits: 0, groupLength: 3 } },
		],
		"unicorn/prefer-keyboard-event-key": "error",
		"unicorn/prefer-logical-operator-over-ternary": "error",
		"unicorn/prefer-node-protocol": "error",
		"unicorn/prefer-number-properties": "error",
		"unicorn/prefer-regexp-test": "error",
		"unicorn/prefer-spread": "error",
		"unicorn/prefer-string-replace-all": "error",
		"unicorn/prefer-string-slice": "error",
		"unicorn/prefer-string-starts-ends-with": "error",
		"unicorn/prefer-type-error": "error",
		"unicorn/template-indent": "error",
		"unicorn/throw-new-error": "error",

		// perfectionist, import and key sorting
		"perfect/sort-exports": ["error", { order: "asc", type: "natural" }],
		"perfect/sort-imports": [
			"error",
			{
				order: "asc",
				type: "natural",
				groups: [
					"type",
					["parent-type", "sibling-type", "index-type", "internal-type"],

					"builtin",
					"external",
					"internal",
					["parent", "sibling", "index"],
					"side-effect",
					"object",
					"unknown",
				],
				newlinesBetween: "always",
			},
		],
		"perfect/sort-named-exports": ["error", { order: "asc", type: "natural" }],
		"perfect/sort-named-imports": ["error", { order: "asc", type: "natural" }],
	},
};

export const STYLISTIC_CONFIG: Linter.Config = {
	plugins: {
		style: style,
		import: importPlugin,
	},
	rules: {
		"prettier/prettier": "off",

		"style/array-bracket-spacing": "error",
		"style/arrow-parens": [
			"error",
			"as-needed",
			{
				requireForBlockBody: true,
			},
		],
		"style/arrow-spacing": "error",
		"style/block-spacing": "error",
		"style/comma-dangle": ["error", "always-multiline"],
		"style/comma-spacing": "error",
		"style/comma-style": "error",
		"style/computed-property-spacing": "error",
		"style/dot-location": ["error", "property"],
		"style/eol-last": "error",
		"style/function-call-spacing": "error",
		"style/function-paren-newline": ["error", "consistent"],
		"style/indent": [
			"error",
			2,
			{
				SwitchCase: 1,
			},
		],
		"style/key-spacing": "error",
		"style/keyword-spacing": "error",
		"style/linebreak-style": "error",
		"style/lines-between-class-members": "error",
		"style/max-len": [
			"error",
			{
				code: 120,
				ignoreStrings: true,
				ignoreTemplateLiterals: true,
				ignoreUrls: true,
				tabWidth: 2,
			},
		],
		"style/max-statements-per-line": ["error", { max: 1 }],
		"style/multiline-ternary": ["error", "always-multiline"],
		"style/new-parens": "error",
		"style/no-confusing-arrow": "error",
		"style/no-floating-decimal": "error",
		"style/no-extra-semi": "error",
		"style/no-mixed-operators": "error",
		"style/no-mixed-spaces-and-tabs": "error",
		"style/no-multi-spaces": "error",
		"style/no-tabs": "error",
		"style/no-trailing-spaces": "error",
		"style/no-whitespace-before-property": "error",
		"style/object-curly-spacing": ["error", "always"],
		"style/operator-linebreak": ["error", "before"],
		"style/quote-props": ["error", "consistent-as-needed"],
		"style/quotes": [
			"error",
			"single",
			{ allowTemplateLiterals: "avoidEscape" },
		],
		"style/semi": ["error", "always"],
		"style/space-before-blocks": ["error", "always"],
		"style/spaced-comment": [
			"error",
			"always",
			{
				markers: ["/"],
			},
		],
		"style/template-curly-spacing": "error",

		"import/newline-after-import": "error",
	},
};
